# Generated by Django 3.2.5 on 2021-08-01 14:54

from django.db import migrations, models
import images.validators


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('url', models.FileField(upload_to='resized_images/')),
                ('height', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.FileField(upload_to='images/', validators=[images.validators.validate_file_type]),
        ),
    ]
