# Generated by Django 3.2.5 on 2021-07-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='size',
            field=models.ManyToManyField(related_name='tier', to='tiers.Size'),
        ),
    ]
